---
### Live profile
spring:
  profiles: live
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username.arrangement-manager}
    password: ${spring.datasource.password.arrangement-manager}
    url: ${spring.datasource.url.arrangement-manager}

backbase:
  security:
    mtls:
      enabled: false
    public:
      paths: "/integration-api/**"
  communication:
    services:
      account:
        integration:
          service-id: account-mock
  arrangement:
    product-kinds:
      use-db: false
      kinds:
        BNC:
          name: "BNC account"
          uri: bnc-account
          id: 10
          custom-order: 10

logging:
  level:
    root: INFO
    com:
      backbase: DEBUG
    org:
      apache:
        http:
          wire: DEBUG
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
