# @service=http://localhost:8080/bb-authentication-token-converter-service

@service=http://localhost:8080


# @service=https://app.ca.cse.live.backbaseservices.com

###summary
GET {{service}}/actuator/

###health
GET {{service}}/actuator/health

###liveness
GET {{service}}/actuator/health/liveness

###readiness
GET {{service}}/actuator/health/readiness

###info
GET {{service}}/actuator/info

###mappings
GET {{service}}/actuator/mappings

###configprops
GET {{service}}/actuator/configprops

###env
GET {{service}}/actuator/env

###beans
GET {{service}}/actuator/beans

###conditions
GET {{service}}/actuator/conditions

###conditions
GET {{service}}/actuator/httptrace

###conditions
GET {{service}}/actuator/gateway/routes
Authorization: Basic YWRtaW46YWRtaW4=

