@gateway-end-point=localhost:7777
@auth-service-in-gateway=/api/auth



### LOGIN-manager
POST {{auth-service-in-gateway}}/login
Host: {{gateway-end-point}}
Content-Type: application/x-www-form-urlencoded
Accept: */*
Cache-Control: no-cache
Connection: keep-alive

username=manager
&password=manager
&submit=Login

