logging:
  level:
    root: INFO
management:
  endpoint:
    beans.enabled: true
  endpoints:
    web.exposure.include: "*"

---
### Live profile
spring:
  profiles: live
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username.accesscontrol-pandp-service}
    password: ${spring.datasource.password.accesscontrol-pandp-service}
    url: ${spring.datasource.url.accesscontrol-pandp-service}

backbase:
  security:
    mtls:
      enabled: false
    public:
      paths: "/**"
  accesscontrol:
    token:
      expiration: 1000
      initPhrase: RandomInitVecto2
      key: Bar12345Bar12345


#     com:
#       backbase: DEBUG
#     org:
#       apache:
#         http:
#           wire: DEBUG
#       springframework:
#         web:
#           filter:
#             CommonsRequestLoggingFilter: DEBUG