---
### Live profile
spring:
  profiles: live

# logging:
#   level:
#     org:
#       apache:
#         http:
#           wire: DEBUG
#       springframework:
#         web:
#           filter:
#             CommonsRequestLoggingFilter: DEBUG


backbase:
  api:
    extensions:
      classes:
        com.backbase.integration.legalentity.rest.spec.v2.legalentities.LegalEntitiesPostRequestBody: additional-data
        com.backbase.integration.legalentity.rest.spec.v2.legalentities.LegalEntitiesPutRequestBody: additional-data
        com.backbase.integration.legalentity.rest.spec.v2.legalentities.CreateLegalEntitiesPostRequestBody: additional-data
      property-sets:
        additional-data:
          properties:
            - property-name: formattedFullAddress
              type: string
            - property-name: streetNumber
              type: string
            - property-name: streetTypeDesignator
              type: string
            - property-name: streetDirectionDesignator
              type: string
            - property-name: streetName
              type: string
            - property-name: streetUnitDesignator
              type: string
            - property-name: streetUnitNumber
              type: string
            - property-name: city
              type: string
            - property-name: country
              type: string
            - property-name: province
              type: string
            - property-name: postalCode
