---
### Live profile
spring:
  profiles: live

logging:
  level:
    org:
      apache:
        http:
          wire: DEBUG
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
